services:
  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "2001:5432"
    network_mode: "host"

  web-server:
    image: sofiatejerina/my-bday-backend:latest
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "2002:80"
    environment:
      - DATABASE_PORT=2001
    network_mode: "host"

  web-app:
    image: sofiatejerina/my-bday-frontend:latest
    restart: unless-stopped
    depends_on:
      - web-server
    ports:
      - "2003:3000"
    environment:
      - BACKEND_PORT=2002
    command: npm run dev
    network_mode: "host"
